graasp/graasp-deploy

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
- caller-workflow-templates/cdelivery-ecs-backend-caller.yml
- caller-workflow-templates/cdeployment-ecs-backend-caller.yml
- caller-workflow-templates/cintegration-ecs-backend-caller.yml
I refactored the backend workflows and moved some env variables to the inputs section. This is due to the restriction the repository has for the amount of secrets (100 in total). Therefore, the variables which are not considered secrets have been moved to the inputs section
> refactor: move env variables to input section

- .github/workflows/update-staging-version.yml
This refactoring improves workflow efficiency, so the yarn dependencies are cached and don't need to be installed every time.
> feat: add yarn cache to improve workflow speed

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdelivery-ecs-explorer.yml
- .github/workflows/cdelivery-ecs.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cdeployment-ecs-explorer.yml
- .github/workflows/cdeployment-ecs.yml
- .github/workflows/cintegration-ecs-backend.yml
- .github/workflows/cintegration-ecs-explorer.yml
- .github/workflows/cintegration-ecs.yml
- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
- .github/workflows/update-staging-stack.yml
- .github/workflows/update-staging-version.yml
This PR addresses the deprecation warning about using `set-output` in workflows.
Fixes #61
> fix: `set-output` deprecation warning

- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
This PR updates the version of `actions/setup-python` to use the latest `v4` which uses node 16 by default.
closes #59
> fix: update setup-python action version

- .github/workflows/release-please.yml
[Release-Please](https://github.com/googleapis/release-please/blob/main/README.md) allows to release via GitHub Actions and tracks release via PRs.
closes #60
> feat: add release-please workflow

- .github/workflows/staging-test.yml
- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
- .github/workflows/update-staging-stack.yml
This PR updates the automatic commits to use conventional commits so that they will not trigger a bump in standard version.
Those commits are now marked as `chore` with a scope when it applies.
closes #69
> fix: update commit messages to follow conventional commits

- .github/workflows/release-please.yml
This PR adds support to make the major `v1` and minor `v1.2` follow the latest release so we can use `v1` in the workflows and always have the latest version.
> feat: add minor and major tag follow after releasing

- .github/workflows/trigger-prod.yml
- scripts/compare.py
This PR is a hot-fix for the failed deploy to prod workflow.
The bug was introduced in #62 when changing from `set-output` to the new convention and using double quotes which disabled the substitution.
Solution was to remove the indentation when generating the file in python.
closes #79
> fix(ci): remove indentation from diff.json and following minification

- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
This PR improves the formatting of the step summary showing the new stack.
- Pairs of repo-tag should now be show one per line (adding double spaces and new line between outputs).
- `echo` also uses double quotes to stay consistant.
closes #88
> chore(fmt): improve formatting of new stack output

- .github/workflows/update-staging-stack.yml
This PR improves the step summary when updating the staging stack to indicate which repo with which tag was updated.
closes #99
> fix: summary step update staging stack

- .github/workflows/trigger-stage.yml
This PR attempts to fix the issue that we need to pull when there are new commits while the trigger staging stack workflow is supended.
closes #110
> fix: checkout latest commits of main branch after suspend in staging

- .github/workflows/update-staging-stack.yml
This PR fixes a minor display bug and adds the missing env vars in the update-staging-version workflow.
closes #107
> fix: add missing env vars in update-staging-version workflow

- .github/workflows/update-staging-version.yml
This PR runs the push tag with the `--no-verify` flag to skip hooks.
closes #112
> feat: add no-verify in push tag workflow

- .github/workflows/update-staging-stack.yml
- README.md
- current/index.html
- current/main.js
This PR adds a view of the current deployments under `/current` in the github-pages deployement.
closes #125
> 125 visualize deployements

- .github/workflows/update-staging-stack.yml
This PR should fix the summary output of the update staging stack workflow that was missing the tag display.
closes #140
> fix: step summary with tag

- .github/actions/auto-tag-after-release/action.yml
This PR adds a composite workflow which should be used after the release please action.
It will automaticaly label all `un-released` issues and prs with the newly created release tag.
> feat: add  auto-tag-after-release composite workflow

- .github/actions/auto-tag-after-release/action.yml
Fix issues with parsing titles in auto-tag-after-release composite action.
In this PR:
- get issues and prs `number` first
- change labels 
- once done, get all tagged issues and prs and format the output using a template
> fix: issues in auto-tag-after-release action

- .github/workflows/cdelivery-ecs-library.yml
- .github/workflows/cdeployment-ecs-library.yml
- .github/workflows/cintegration-ecs-library.yml
This PR adds the env var to toggle the `NEXT_PUBLIC_SHOW_NOTIFICATIONS` that controls whether the toasts are allowed.
> fix: add `next-public-show-notifications` in library deploy workflows

- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
This PR updates the auto-schedules for the staging and production deployments.
We will deploy Staging on Thursdays (9AM)
We will deploy prod on Mondays (9AM)
This will allow us to test staging during the weekend and fix any bugs we might encounter before pushing to prod on monday.
> chore: invert staging and prod schedule

- .github/workflows/library-deploy-dev.yml
- .github/workflows/library-deploy-prod.yml
- .github/workflows/library-deploy-stage.yml
This PR:
- add sentry ENV secret to library deploy workflows
- rename library deploy workflows to use simpler names
- remove unused global env variables
> fix: rename and adapt ecs workflows

- .github/actions/pnpm-install-and-cache/action.yml
In this PR I create a composite action that can be used to install dependencies using pnpm. This workflow is similar to the `yarn-install-and-cache` but for pnpm.
> fix: add pnpm install and cache action

- .github/workflows/notify-new-candidate-version.yml
If two new versions are dispatched to the repo nearly simultaneously then the first one will get cancelled by the second one. This is not expected, we want only a single one running, but the new one should not cancel the other.
> fix: update-version cancels running workflows

- .gitignore
- scripts/compare.py
In this PR:
- update the compare script to output a `diff.json` that is empty even when there are no changes.
This allows the CI logic to no break and to correctly output the "No changes 💩 detected" message.
> fix: update the compare script to emit a file even when there is no differences
