- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdelivery-s3.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cdeployment-s3.yml
- .github/workflows/cintegration-ecs-backend.yml
- .github/workflows/cintegration-s3.yml
- caller-workflow-templates/cdelivery-ecs-backend-caller.yml
- caller-workflow-templates/cdelivery-s3-apps-caller.yml
- caller-workflow-templates/cdeployment-ecs-backend-caller.yml
- caller-workflow-templates/cdeployment-s3-caller.yml
- caller-workflow-templates/cintegration-ecs-backend-caller.yml
- caller-workflow-templates/cintegration-s3-caller.yml
I added an additional variable for the frontend (used in graasp account).
I also sorted the variables in alphabetical order.
close #13
> refactor: add stripe front env variable

- .github/workflows/cdelivery-ecs-explorer.yml
- .github/workflows/cdeployment-ecs-explorer.yml
- .github/workflows/cintegration-ecs-explorer.yml
- caller-workflow-templates/cdelivery-ecs-explorer-caller.yml
- caller-workflow-templates/cdeployment-ecs-explorer-caller.yml
- caller-workflow-templates/cintegration-ecs-explorer-caller.yml
> refactor: add domain for explorer

- .github/workflows/cdelivery-s3-apps.yml
- .github/workflows/cdelivery-s3.yml
- .github/workflows/cdeployment-s3-apps.yml
- .github/workflows/cdeployment-s3.yml
- .github/workflows/cintegration-s3-apps.yml
- .github/workflows/cintegration-s3.yml
- caller-workflow-templates/cdelivery-s3-apps-caller.yml
- caller-workflow-templates/cdelivery-s3-caller.yml
- caller-workflow-templates/cdeployment-s3-apps-caller.yml
- caller-workflow-templates/cdeployment-s3-caller.yml
- caller-workflow-templates/cintegration-s3-apps-caller.yml
- caller-workflow-templates/cintegration-s3-caller.yml
> refactor: rename sentry env for s3

- .github/workflows/cdelivery-s3.yml
- .github/workflows/cdeployment-s3.yml
- .github/workflows/cintegration-s3.yml
- caller-workflow-templates/cdelivery-s3-caller.yml
- caller-workflow-templates/cdeployment-s3-caller.yml
- caller-workflow-templates/cintegration-s3-caller.yml
> feat: add h5p integration url

- .github/workflows/update-staging-version.yml
Fix issue raised when pushing a tag because of the insufficient heap size
> fix: increase the memory size

- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
The workflow will show a badge with a link to every repository that is dispatched to improve UX
> feat: add badge with link to workflow

- .github/workflows/cdelivery-ecs-explorer.yml
- .github/workflows/cdeployment-ecs-explorer.yml
- .github/workflows/cintegration-ecs-explorer.yml
> refactor: add app version and name to library

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
> refactor: add hidden items plugin input to backend caller

- .github/workflows/cdelivery-s3-apps.yml
- .github/workflows/cdelivery-s3.yml
- .github/workflows/cdeployment-s3-apps.yml
- .github/workflows/cdeployment-s3.yml
- .github/workflows/cintegration-s3-apps.yml
- .github/workflows/cintegration-s3.yml
- .github/workflows/cypress.yml
> refactor: add GENERATE_SOURCEMAP

- Readme.md
This PR adds a badge on the readme to indicate the latest version of he workflow that we provide.
The Readme file was also formatted, so this explains the noise in the diff.
closes #77
> chore(docs): add badge to readme

- .github/workflows/trigger-prod.yml
- .github/workflows/trigger-stage.yml
This PR adds missing fixes to the stage and prod workflows.
closes #79
> fix: remaining substitutions and schenanigans

- .github/workflows/cdelivery-ecs-library.yml
- .github/workflows/cdeployment-ecs-library.yml
- .github/workflows/cintegration-ecs-library.yml
> 90 library

- .github/actions/yarn-install-and-cache/action.yml
- .github/workflows/cdelivery-s3-apps.yml
- .github/workflows/cdelivery-s3.yml
- .github/workflows/cdeployment-s3-apps.yml
- .github/workflows/cdeployment-s3.yml
- .github/workflows/cintegration-s3-apps.yml
- .github/workflows/cintegration-s3.yml
- .github/workflows/cypress.yml
- .github/workflows/update-staging-version.yml
> 72 cache workflow

- .github/actions/yarn-install-and-cache/action.yml
> fix: remove restore keys for node modules

- .github/workflows/cypress.yml
> fix: add checkout in install step in cypress.yml

- .github/workflows/cdelivery-s3.yml
- .github/workflows/cdeployment-s3.yml
- .github/workflows/cintegration-s3.yml
> fix: fix google maps key

- .github/actions/publish-to-npm/action.yml
This PR adds a composite action to publish to NPM.
closes #121
> feat: add composite action

- .github/actions/publish-to-npm/action.yml
This PR fixes a bug in the compose action to publish with NPM.
closes #129
> fix: add shell to script run

- .github/actions/publish-to-npm/action.yml
This PR fixes the problem that secrets are not accessible in composites, we will get the token from inputs.
closes #129
> Fix secrets can't be used in composite actions

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
Related to https://github.com/graasp/graasp/pull/288
> feat: add PG_READ_REPLICAS_CONNECTION_URIS secret

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
> feat: add etherpad env vars

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
> feat: add etherpad cookie domain input

- .github/workflows/cdelivery-ecs-library.yml
- .github/workflows/cdeployment-ecs-library.yml
- .github/workflows/cintegration-ecs-library.yml
- .github/workflows/cypress.yml
> feat: add analytics host to library workflows

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
> feat: add sentry DSN secret

- .github/workflows/cdelivery-ecs-library.yml
- .github/workflows/cdeployment-ecs-library.yml
- .github/workflows/cintegration-ecs-library.yml
- .github/workflows/update-staging-stack.yml
Also fix #157 by checking out main
closes #158
closes #157
> fix: remove legacy ga env vars

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
https://github.com/graasp/graasp/pull/325 now allows splitting Sentry events using the deployment environment. This PR adds the relevant environment variable
> feat: add DEPLOY_ENV var

- .github/workflows/deploy-refactor.yml
Based on https://github.com/graasp/graasp-deploy/pull/153
> Create refactor reusable workflow using env vars and secrets

- .github/workflows/deploy-refactor.yml
This PR adds (updates) the refactor deployment that uses Github environment's variables.
> Refactor deploy

- .github/actions/auto-tag-after-release/action.yml
- .github/workflows/auto-tag.yml
- feat: add re-usable auto-tag workflow
- fix: remove missleading hashtag
> Create re-usable workflow for auto-tag

- postman/GraaspSmokeTest.postman_collection.json
This PR updates the Postman tests to test for the correct value of the page titles.
> fix: postman tests expect title of page

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
Update workflows for typeorm to deploy on all environments.
DO NOT MERGE UNLESS WE'RE READY TO DEPLOY ON STAGING+PROD
> feat: update backend deployment workflows for typeorm

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
I added environments because we reached the maximum of variables for the repo.
I've only added what I needed, which are the db settings.
> refactor: add environments to backend workflows

- docs/maintenance.md
Some explanation on how to do maintenance with the current method
> Maintenance doc

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
- .github/workflows/deploy-refactor.yml
to update CI after https://github.com/graasp/graasp/pull/475
> chore: rename .stagingcontainer to docker

- .github/workflows/cdelivery-ecs-backend.yml
- .github/workflows/cdeployment-ecs-backend.yml
- .github/workflows/cintegration-ecs-backend.yml
Related to https://github.com/graasp/graasp/pull/471
Also performs some formatting
> feat: replace EMAIL_LINKS_HOST by PUBLIC_URL and pluralize DB_READ_REPLICA_HOSTS
